name: Dizi

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v4

    - name: Python ve yt-dlp Kurulumu
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade yt-dlp

    - name: M3U8 Dosyalarını Oluştur
      run: |
        mkdir -p dizi

        channels=(
          "cennetmahallesi https://www.youtube.com/@cennetmahallesishowtv/live"
          "behzatc https://www.youtube.com/@Behzatc./live"
          "yenigelin https://www.youtube.com/@yenigelindizi/live"
          "sihirliannem https://www.youtube.com/@SihirliAnnemDizi/live"
          "eeesonra https://www.youtube.com/@EeeSonra/live"
          "sefirinkizi https://www.youtube.com/@sefirinkizidizi/live"
          "avlu https://www.youtube.com/@avludizi/live"
          "cilekkokusu https://www.youtube.com/@CilekKokusu/live"
          "fazilethanimvekizlari https://www.youtube.com/@fazilethanimvekizlaridizi/live"
          "hanimkoylu https://www.youtube.com/@HanimKoyluDizi/live"
          "hayatbazentatlidir https://www.youtube.com/@HayatBazenTatlidir/live"
          "ufaktefekcinayetler https://www.youtube.com/@ufaktefekcinayetlerdizi/live"
          "istanbullugelin https://www.youtube.com/@istanbullugelindizi/live"
        )

        for item in "${channels[@]}"; do
          name=$(echo $item | cut -d' ' -f1)
          url=$(echo $item | cut -d' ' -f2)
          
          echo "Yayın taranıyor: $name ..."
          stream_url=$(yt-dlp --print urls "$url" || echo "")
          
          if [ -n "$stream_url" ]; then
            echo "#EXTM3U" > "./dizi/${name}.m3u8"
            echo "#EXT-X-VERSION:3" >> "./dizi/${name}.m3u8"
            echo "#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000" >> "./dizi/${name}.m3u8"
            echo "$stream_url" >> "./dizi/${name}.m3u8"
            echo "✅ $name.m3u8 oluşturuldu."
          else
            echo "❌ Canlı yayın bulunamadı: $name"
          fi
        done

    - name: Commit & Push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add dizi/
        if ! git diff --cached --quiet; then
          git commit -m "updated streams $(date +'%Y-%m-%d %H:%M:%S') [skip ci]"
          git push
        else
          echo "Değişiklik yok, commit/push atlanıyor."
        fi
